<?php
use Drupal\library\Library;
use Symfony\Component\Yaml\Yaml;

if ( ! function_exists('di') ) {
    function di($obj)
    {
        echo '<pre>';
        print_r($obj);
        echo '</pre>';
    }
}
/*for automatic routing by #theme*/
function library_theme()
{
  $routes = Yaml::parse(file_get_contents(drupal_get_path('module', 'library').'/library.routing.yml'));   
  
  $themes = [];
  foreach($routes as $name => $info) {
    $themes[$name] = [
      'variables' => [ 'data' => null],
      'template' => $name
    ];
		
  }

  return $themes;
}

function library_preprocess( &$variables, $hook )
{

    // Library::error(-999, \Drupal\library\Language::string('library', 'version')); // test

    $variables['error'] = Library::getError();



    if ( Library::isLibraryCategoryPage() ) {
        $variables['#attached']['library'][] = 'library/category';
    }

}


$error_information = [];
function error($code, $info)
{
    global $error_information;
    $error_information[$code] = $info;
    return $code;
}
function get_error($code)
{
    global $error_information;
    return $error_information[$code];
}