<?php
use Symfony\Component\Yaml\Yaml;


$error_information = [];


if ( ! function_exists('di') ) {
    function di($obj)
    {
        echo '<pre>';
        print_r($obj);
        echo '</pre>';
    }
}
/*for automatic routing by #theme*/
function library_theme()
{
  $routes = Yaml::parse(file_get_contents(drupal_get_path('module', 'library').'/library.routing.yml'));   
  
  $themes = [];
  foreach($routes as $name => $info) {
    $themes[$name] = [
      'variables' => [ 'data' => null],
      'template' => $name
    ];
		
  }
  
  return $themes;
}

function library_preprocess( &$variables, $hook ){
	$variables['#attached']['library'][] = 'library/default';
}


function error($code, $info)
{
    global $error_information;
    $error_information[$code] = $info;
    return $code;
}
function get_error($code)
{
    global $error_information;
    return $error_information[$code];
}